#!/usr/bin/env bash

cd auth_server
bundle exec rails db:create db:migrate db:seed

cd ../client
bundle exec rails db:create db:migrate db:seed

cd ../protected_resource
bundle exec rails db:create db:migrate db:seed

cd ..