source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.0"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.4"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem "rack-cors", "~> 1.1.1"

# Use Faraday for making HTTP requests
gem "faraday", "~> 2.7.2"

# Use Configatron to manage app configuration
gem "configatron", "~> 4.5.1"

group :development, :test do
  # Use byebug instead of debugger because it can exit without crashing the app.
  gem "byebug", "~> 11.1"

  # Use RSpec for testing
  gem "rspec-rails", "~> 6.0.1"

  # Use FactoryBot for test data
  gem "factory_bot_rails", "~> 6.2.0"
end
