#!/usr/bin/env bash

cd auth_server
bundle exec rails db:truncate_all db:seed

cd ../client
bundle exec rails db:truncate_all db:seed

cd ../protected_resource
bundle exec rails db:truncate_all db:seed

cd ..